[package]
name = "better_kt_sqep"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
im = "15.1.0"
quick-xml = { version = "0.37.2", features = ["serde", "serialize"] }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"

[dev-dependencies]
regex = "1.11.1"
